In [5]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
%matplotlib inline 

In [22]:
# Importing the dataset
dataset = pd.read_csv('./titanicTrain.csv')
dataset

pclass  survived                                               name  \
0         1         1                      Allen, Miss. Elisabeth Walton   
1         1         1                     Allison, Master. Hudson Trevor   
2         1         0                       Allison, Miss. Helen Loraine   
3         1         0               Allison, Mr. Hudson Joshua Creighton   
4         1         0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
5         1         1                                Anderson, Mr. Harry   
6         1         1                  Andrews, Miss. Kornelia Theodosia   
7         1         0                             Andrews, Mr. Thomas Jr   
8         1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
9         1         0                            Artagaveytia, Mr. Ramon   
10        1         0                             Astor, Col. John Jacob   
11        1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
12        1         1                      Aubart, Mme. Leontine Pauline   
13        1         1                       Barber, Miss. Ellen "Nellie"   
14        1         1               Barkworth, Mr. Algernon Henry Wilson   
15        1         0                                Baumann, Mr. John D   
16        1         0                           Baxter, Mr. Quigg Edmond   
17        1         1    Baxter, Mrs. James (Helene DeLaudeniere Chaput)   
18        1         1                              Bazzani, Miss. Albina   
19        1         0                               Beattie, Mr. Thomson   
20        1         1                      Beckwith, Mr. Richard Leonard   
21        1         1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
22        1         1                              Behr, Mr. Karl Howell   
23        1         1                              Bidois, Miss. Rosalie   
24        1         1                                  Bird, Miss. Ellen   
25        1         0                                Birnbaum, Mr. Jakob   
26        1         1                            Bishop, Mr. Dickinson H   
27        1         1            Bishop, Mrs. Dickinson H (Helen Walton)   
28        1         1                             Bissette, Miss. Amelia   
29        1         1          Bjornstrom-Steffansson, Mr. Mauritz Hakan   
..      ...       ...                                                ...   
970       3         1                        Lindqvist, Mr. Eino William   
971       3         0                               Linehan, Mr. Michael   
972       3         0                                      Ling, Mr. Lee   
973       3         0                                 Lithman, Mr. Simon   
974       3         0                           Lobb, Mr. William Arthur   
975       3         0    Lobb, Mrs. William Arthur (Cordelia K Stanlick)   
976       3         0                                Lockyer, Mr. Edward   
977       3         0                    Lovell, Mr. John Hall ("Henry")   
978       3         1                                  Lulic, Mr. Nikola   
979       3         0                        Lundahl, Mr. Johan Svensson   
980       3         1                           Lundin, Miss. Olga Elida   
981       3         1                         Lundstrom, Mr. Thure Edvin   
982       3         0                              Lyntakoff, Mr. Stanko   
983       3         0                         MacKay, Mr. George William   
984       3         1                   Madigan, Miss. Margaret "Maggie"   
985       3         1                          Madsen, Mr. Fridtjof Arne   
986       3         0                      Maenpaa, Mr. Matti Alexanteri   
987       3         0                         Mahon, Miss. Bridget Delia   
988       3         0                                    Mahon, Mr. John   
989       3         0                                 Maisner, Mr. Simon   
990       3         0                          Makine

In [23]:
def sexturn(s):
    if s == 'female':
        return 0
    elif s == 'male':
        return 1
    else:
        return 2
dataset['sex']=dataset['sex'].apply(sexturn)
dataset

pclass  survived                                               name  sex  \
0         1         1                      Allen, Miss. Elisabeth Walton    0   
1         1         1                     Allison, Master. Hudson Trevor    1   
2         1         0                       Allison, Miss. Helen Loraine    0   
3         1         0               Allison, Mr. Hudson Joshua Creighton    1   
4         1         0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)    0   
5         1         1                                Anderson, Mr. Harry    1   
6         1         1                  Andrews, Miss. Kornelia Theodosia    0   
7         1         0                             Andrews, Mr. Thomas Jr    1   
8         1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)    0   
9         1         0                            Artagaveytia, Mr. Ramon    1   
10        1         0                             Astor, Col. John Jacob    1   
11        1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)    0   
12        1         1                      Aubart, Mme. Leontine Pauline    0   
13        1         1                       Barber, Miss. Ellen "Nellie"    0   
14        1         1               Barkworth, Mr. Algernon Henry Wilson    1   
15        1         0                                Baumann, Mr. John D    1   
16        1         0                           Baxter, Mr. Quigg Edmond    1   
17        1         1    Baxter, Mrs. James (Helene DeLaudeniere Chaput)    0   
18        1         1                              Bazzani, Miss. Albina    0   
19        1         0                               Beattie, Mr. Thomson    1   
20        1         1                      Beckwith, Mr. Richard Leonard    1   
21        1         1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)    0   
22        1         1                              Behr, Mr. Karl Howell    1   
23        1         1                              Bidois, Miss. Rosalie    0   
24        1         1                                  Bird, Miss. Ellen    0   
25        1         0                                Birnbaum, Mr. Jakob    1   
26        1         1                            Bishop, Mr. Dickinson H    1   
27        1         1            Bishop, Mrs. Dickinson H (Helen Walton)    0   
28        1         1                             Bissette, Miss. Amelia    0   
29        1         1          Bjornstrom-Steffansson, Mr. Mauritz Hakan    1   
..      ...       ...                                                ...  ...   
970       3         1                        Lindqvist, Mr. Eino William    1   
971       3         0                               Linehan, Mr. Michael    1   
972       3         0                                      Ling, Mr. Lee    1   
973       3         0                                 Lithman, Mr. Simon    1   
974       3         0                           Lobb, Mr. William Arthur    1   
975       3         0    Lobb, Mrs. William Arthur (Cordelia K Stanlick)    0   
976       3         0                                Lockyer, Mr. Edward    1   
977       3         0                    Lovell, Mr. John Hall ("Henry")    1   
978       3         1                                  Lulic, Mr. Nikola    1   
979       3         0                        Lundahl, Mr. Johan Svensson    1   
980       3         1                           Lundin, Miss. Olga Elida    0   
981       3         1                         Lundstrom, Mr. Thure Edvin    1   
982       3         0                              Lyntakoff, Mr. Stanko    1   
983       3         0                         MacKay, Mr. George William    1   
984       3         1                   Madigan, Miss. Margaret "Maggie"    0   
985       3         1                          Madsen, Mr. Fridtjof Arne    1   
986       3         0                      Maenpaa, Mr. Matti Alexanteri    1   
987       3         0               

In [29]:
dataset[['pclass','survived','sex','sibsp']].corr()

pclass  survived       sex     sibsp
pclass    1.000000 -0.307329  0.126060  0.034437
survived -0.307329  1.000000 -0.557571  0.035458
sex       0.126060 -0.557571  1.000000 -0.160844
sibsp     0.034437  0.035458 -0.160844  1.000000

In [68]:
X = dataset[['pclass','sex','sibsp']].values
X

array([[1, 0, 0],
       [1, 1, 1],
       [1, 0, 1],
       ...,
       [3, 0, 0],
       [3, 1, 0],
       [3, 0, 0]], dtype=int64)

In [69]:
y = dataset['survived'].values
y

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,

In [70]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 0)


In [71]:
X_train.shape

(500, 3)

In [72]:
y_train.shape

(500,)

In [73]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [74]:
len(y_pred)

500

In [75]:
surv=0
for i in range(len(y_pred)):
    if y_test[i]==y_pred[i]:
        surv+=1
surv/=len(y_pred)
surv

0.794

In [76]:
cm

array([[247,  33],
       [ 70, 150]], dtype=int64)

In [66]:
dataset_Q = pd.read_csv('./titanicQuestion.csv')
dataset_Q

pclass  survived                                             name  \
0         3       NaN                     McCormack, Mr. Thomas Joseph   
1         3       NaN                               McCoy, Miss. Agnes   
2         3       NaN                              McCoy, Miss. Alicia   
3         3       NaN                               McCoy, Mr. Bernard   
4         3       NaN                   McDermott, Miss. Brigdet Delia   
5         3       NaN                              McEvoy, Mr. Michael   
6         3       NaN                             McGovern, Miss. Mary   
7         3       NaN                      McGowan, Miss. Anna "Annie"   
8         3       NaN                         McGowan, Miss. Katherine   
9         3       NaN                              McMahon, Mr. Martin   
10        3       NaN                                McNamee, Mr. Neal   
11        3       NaN              McNamee, Mrs. Neal (Eileen O'Leary)   
12        3       NaN                           McNeill, Miss. Bridget   
13        3       NaN                   Meanwell, Miss. (Marion Ogden)   
14        3       NaN          Meek, Mrs. Thomas (Annie Louise Rowley)   
15        3       NaN                                 Meo, Mr. Alfonzo   
16        3       NaN                              Mernagh, Mr. Robert   
17        3       NaN                         Midtsjo, Mr. Karl Albert   
18        3       NaN                                 Miles, Mr. Frank   
19        3       NaN                                 Mineff, Mr. Ivan   
20        3       NaN                               Minkoff, Mr. Lazar   
21        3       NaN                            Mionoff, Mr. Stoytcho   
22        3       NaN                                Mitkoff, Mr. Mito   
23        3       NaN                Mockler, Miss. Helen Mary "Ellie"   
24        3       NaN                          Moen, Mr. Sigurd Hansen   
25        3       NaN                              Moor, Master. Meier   
26        3       NaN                               Moor, Mrs. (Beila)   
27        3       NaN                       Moore, Mr. Leonard Charles   
28        3       NaN                              Moran, Miss. Bertha   
29        3       NaN                              Moran, Mr. Daniel J   
..      ...       ...                                              ...   
279       3       NaN             Vestrom, Miss. Hulda Amanda Adolfina   
280       3       NaN                                  Vovk, Mr. Janko   
281       3       NaN                             Waelens, Mr. Achille   
282       3       NaN                              Ware, Mr. Frederick   
283       3       NaN                      Warren, Mr. Charles William   
284       3       NaN                                Webber, Mr. James   
285       3       NaN                              Wenzel, Mr. Linhart   
286       3       NaN  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
287       3       NaN                 Widegren, Mr. Carl/Charles Peter   
288       3       NaN                        Wiklund, Mr. Jakob Alfred   
289       3       NaN                          Wiklund, Mr. Karl Johan   
290       3       NaN                 Wilkes, Mrs. James (Ellen Needs)   
291       3       NaN                 Willer, Mr. Aaron ("Abi Weller")   
292       3       NaN                               Willey, Mr. Edward   
293       3       NaN                Williams, Mr. Howard Hugh "Harry"   
294       3       NaN                             Williams, Mr. Leslie   
295       3       NaN                              Windelov, Mr. Einar   
296       3       NaN                                 Wirz, Mr. Albert   
297       3       NaN                           Wiseman, Mr. Phillippe   
298       3       NaN                        Wittevrongel, Mr. Camille   
299       3       NaN                              Yasbeck, Mr. Antoni   
300       3       NaN          Yasbeck, Mrs. Antoni (Selini Alexander)   
301      

In [77]:
def sexturn(s):
    if s == 'female':
        return 0
    elif s == 'male':
        return 1
    else:
        return 2
dataset_Q['sex']=dataset_Q['sex'].apply(sexturn)
dataset_Q

pclass  survived                                             name  sex  \
0         3       NaN                     McCormack, Mr. Thomas Joseph    1   
1         3       NaN                               McCoy, Miss. Agnes    0   
2         3       NaN                              McCoy, Miss. Alicia    0   
3         3       NaN                               McCoy, Mr. Bernard    1   
4         3       NaN                   McDermott, Miss. Brigdet Delia    0   
5         3       NaN                              McEvoy, Mr. Michael    1   
6         3       NaN                             McGovern, Miss. Mary    0   
7         3       NaN                      McGowan, Miss. Anna "Annie"    0   
8         3       NaN                         McGowan, Miss. Katherine    0   
9         3       NaN                              McMahon, Mr. Martin    1   
10        3       NaN                                McNamee, Mr. Neal    1   
11        3       NaN              McNamee, Mrs. Neal (Eileen O'Leary)    0   
12        3       NaN                           McNeill, Miss. Bridget    0   
13        3       NaN                   Meanwell, Miss. (Marion Ogden)    0   
14        3       NaN          Meek, Mrs. Thomas (Annie Louise Rowley)    0   
15        3       NaN                                 Meo, Mr. Alfonzo    1   
16        3       NaN                              Mernagh, Mr. Robert    1   
17        3       NaN                         Midtsjo, Mr. Karl Albert    1   
18        3       NaN                                 Miles, Mr. Frank    1   
19        3       NaN                                 Mineff, Mr. Ivan    1   
20        3       NaN                               Minkoff, Mr. Lazar    1   
21        3       NaN                            Mionoff, Mr. Stoytcho    1   
22        3       NaN                                Mitkoff, Mr. Mito    1   
23        3       NaN                Mockler, Miss. Helen Mary "Ellie"    0   
24        3       NaN                          Moen, Mr. Sigurd Hansen    1   
25        3       NaN                              Moor, Master. Meier    1   
26        3       NaN                               Moor, Mrs. (Beila)    0   
27        3       NaN                       Moore, Mr. Leonard Charles    1   
28        3       NaN                              Moran, Miss. Bertha    0   
29        3       NaN                              Moran, Mr. Daniel J    1   
..      ...       ...                                              ...  ...   
279       3       NaN             Vestrom, Miss. Hulda Amanda Adolfina    0   
280       3       NaN                                  Vovk, Mr. Janko    1   
281       3       NaN                             Waelens, Mr. Achille    1   
282       3       NaN                              Ware, Mr. Frederick    1   
283       3       NaN                      Warren, Mr. Charles William    1   
284       3       NaN                                Webber, Mr. James    1   
285       3       NaN                              Wenzel, Mr. Linhart    1   
286       3       NaN  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)    0   
287       3       NaN                 Widegren, Mr. Carl/Charles Peter    1   
288       3       NaN                        Wiklund, Mr. Jakob Alfred    1   
289       3       NaN                          Wiklund, Mr. Karl Johan    1   
290       3       NaN                 Wilkes, Mrs. James (Ellen Needs)    0   
291       3       NaN                 Willer, Mr. Aaron ("Abi Weller")    1   
292       3       NaN                               Willey, Mr. Edward    1   
293       3       NaN                Williams, Mr. Howard Hugh "Harry"    1   
294       3       NaN                             Williams, Mr. Leslie    1   
295       3       NaN                              Windelov, Mr. Einar    1   
296       3       NaN                                 Wirz, Mr. Albert    1   
297       3       NaN                           Wiseman

In [80]:
X_Q = dataset_Q[['pclass','sex','sibsp']].values
X_Q

array([[3, 1, 0],
       [3, 0, 2],
       [3, 0, 2],
       [3, 1, 2],
       [3, 0, 0],
       [3, 1, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 1, 0],
       [3, 1, 1],
       [3, 0, 1],
       [3, 0, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 0, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 0, 0],
       [3, 1, 0],
       [3, 0, 1],
       [3, 1, 1],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 1],
       [3, 1, 1],
       [3, 0, 0],
       [3, 0, 0],
       [3, 1, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 1, 0],
       [3, 0, 1],
       [3, 0, 1],
       [3, 0, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 1, 1],
       [3, 0, 1],
       [3, 1, 0],
       [3, 1, 0],
       [3, 1, 0],
       [3, 0, 0],
       [3,

In [81]:
y_Q_pred = classifier.predict(X_Q)
y_Q_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [82]:
len(y_Q_pred)

309